### ISSUE TITLE
[FEATURE REQUEST] Provide official flatpak/flathub package

### ISSUE THREAD

**Issue by AlxHnr** [freemocap/freemocap#683]
**Is your feature request related to a problem? Please describe.**

Fighting with python and pip sucks on some systems. On Alpine Linux one of FreeMoCap's pip dependencies doesn't build with python 3.12 and needs a tedious downgrade to 3.11. The installer from the release page also doesn't work on Alpine.

**Describe the solution you'd like**

Official flathub package for portable one-click installations on all Linux distributions.

**Describe alternatives you've considered**

Upgrade FreeMoCap's pip dependencies so they build with Python 3.12. Usually people don't notice the build is broken due to available prebuild binary packages.

**What is the use case for this feature?**

Increased accessibility. Prevents random fans from creating an unofficial FreeMoCap package which is not controlled by us.

**Additional context**

I've created this manifest as a starting point. Save as `org.freemocap.app.yml`:

```yml
id: org.freemocap.app
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: freemocap
modules:
  - name: freemocap
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
    build-commands:
      - pip install --prefix=${FLATPAK_DEST} freemocap
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --device=all
  - --filesystem=host
  - --filesystem=home
```

Build and run with:

```sh
flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir org.freemocap.app.yml
flatpak run org.freemocap.app
```

There are a few bugs and todos related to the manifest above.
* `gui_state.json` is on a read-only filesystem and does not persist
* The fix for conflicting opencv versions also does not persist, maybe there is a better way to take care of this in the manifests build steps
* Building the package needs to be integrated into CI
* Get verified on Flathub to get the official checkmark
